CREATE TABLE KHACHHANG
(
MAKH CHAR(4) primary key,
HOTEN varchar(40),
DCHI varchar(50),
SODT varchar(10),
NGSINH smalldatetime,
NGDK smalldatetime,
DOANHSO money,
);

CREATE TABLE NHANVIEN (
MANV CHAR(4) primary key,
HOTEN VARCHAR(40),
SODT VARCHAR(20),
NGVL smalldatetime,
);



CREATE TABLE SANPHAM(
MASP char(4) primary key,
TENSP varchar(40),
DVT varchar(20),
NUOCSX varchar(40),
GIA money,
);

CREATE TABLE HOADON ( 
SOHD int primary key,
NGHD smalldatetime,
MAKH char(4) REFERENCES KHACHHANG(MAKH),
MANV char(4) REFERENCES NHANVIEN(MANV),
TRIGIA money,
);

CREATE TABLE CTHD (
SOHD INT REFERENCES HOADON(SOHD),
MASP char(4) REFERENCES SANPHAM(MASP),
SL INT CHECK(SL >= 1),
PRIMARY KEY(SOHD, MASP),
);

--2--
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)

--3--
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT

--4--
ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR(100)

--5--
ALTER TABLE SANPHAM DROP COLUMN GHICHU

--6--
ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH VARCHAR(20)
ALTER TABLE KHACHHANG ADD CONSTRAINT CHECK_LOAIKH CHECK(LOAIKH IN('Vang lai', 'Thuong xuyen', 'VIP'))

--7--
ALTER TABLE SANPHAM ADD CONSTRAINT CHECK_DVT CHECK(DVT IN('cay', 'hop', 'cai', 'quyen', 'chuc'))

--8--
ALTER TABLE SANPHAM ADD CONSTRAINT CHECK_GIA CHECK(GIA >= 500)

--9--
ALTER TABLE HOADON ADD CONSTRAINT CHECK_MUAHANG CHECK(TRIGIA > 0)

--10--
ALTER TABLE KHACHHANG ADD CONSTRAINT CHECK_NGAY CHECK(NGDK > NGSINH)
